upgrade:
	helm upgrade -i -f values.yaml demo .

upgrade-eks:
	helm upgrade -i -f values-eks.yaml demo .

delete:
	helm delete demo

template:
	helm template -f values.yaml demo .

template-eks:
	helm template -f values-eks.yaml demo .
